### ISSUE TITLE
[BUG] java.lang.StackOverflowError: null in utils.block.Utilities.findConnectedBlocksOfType

### ISSUE THREAD

**Issue by viveleroi** [prism/PrismRefracted#38]
```
[12:50:44] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Prism v3.0.3
java.lang.StackOverflowError: null
	at net.minecraft.world.level.Level.getChunk(Level.java:636) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:975) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlock.getType(CraftBlock.java:227) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at network.darkhelmet.prism.utils.block.Utilities.findConnectedBlocksOfType(Utilities.java:605) ~[Prism-3.0.3-all.jar:?]
	at network.darkhelmet.prism.utils.block.Utilities.findConnectedBlocksOfType(Utilities.java:607) ~[Prism-3.0.3-all.jar:?]
	at network.darkhelmet.prism.utils.block.Utilities.findConnectedBlocksOfType(Utilities.java:607) ~[Prism-3.0.3-all.jar:?]
	at network.darkhelmet.prism.utils.block.Utilities.findConnectedBlocksOfType(Utilities.java:607) ~[Prism-3.0.3-all.jar:?]
	at network.darkhelmet.prism.utils.block.Utilities.findConnectedBlocksOfType(Utilities.java:607) ~[Prism-3.0.3-all.jar:?]
	at network.darkhelmet.prism.utils.block.Utilities.findConnectedBlocksOfType(Utilities.java:607) ~[Prism-3.0.3-all.jar:?]
```

**Comment by Rothes** [comment]
I received this bug report once a time. But I ignored it because no extra info.
Maybe capture the Exception for more debug info.

**Comment by viveleroi** [comment]
I have no extra info, just noticed it in the logs. The ore alert stuff needs an overhaul anyway. For v4 I was planning to make it a separate plugin. For example it was never designed to work with large veins, it caps at 100 blocks and often re-alerts because the vein was too large.

**Comment by TauCubed** [comment]
I wrote some code to specifically do this with one of my plugins (including corner blocks) I'll pop in a pr later today.

**Comment by viveleroi** [comment]
Closing this PR as Prism v3 is in maintenance-only mode while v4 awaits leaving beta for release.
