### ISSUE TITLE
[BUG] Material cannot be null during inspection wand use

### ISSUE THREAD

**Issue by viveleroi** [prism/PrismRefracted#45]
```
[16:16:17] [Server thread/INFO]: SizzlingBacon5 issued server command: /pr i
[16:16:29] [Craft Scheduler Thread - 2006 - Prism/WARN]: [Prism] Plugin Prism v3.4.0 generated an exception while executing task 5527828
java.lang.IllegalArgumentException: Material cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:97) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:72) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at network.darkhelmet.prism.actions.data.ItemStackActionData.toItem(ItemStackActionData.java:204) ~[Prism-3.4.0-all.jar:?]
	at network.darkhelmet.prism.actions.ItemStackAction.deserialize(ItemStackAction.java:111) ~[Prism-3.4.0-all.jar:?]
	at network.darkhelmet.prism.database.sql.SqlSelectQueryBuilder.executeSelect(SqlSelectQueryBuilder.java:626) ~[Prism-3.4.0-all.jar:?]
	at network.darkhelmet.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:66) ~[Prism-3.4.0-all.jar:?]
	at network.darkhelmet.prism.wands.QueryWandBase.getResult(QueryWandBase.java:75) ~[Prism-3.4.0-all.jar:?]
	at network.darkhelmet.prism.wands.InspectorWand.lambda$showLocationHistory$0(InspectorWand.java:89) ~[Prism-3.4.0-all.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1685]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1685]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Rothes** [comment]
Due to server upgrade? e.g. 1.17 -> 1.19
Some Material enum should be changed.

**Comment by Bobcat00** [comment]
Got the same error with `/pr near`. Strangely, doing `/pr l t:1w r:5` worked just fine.

Paper version git-Paper-138 (MC: 1.19.2)
Prism v3.5.0

```
[WARN] [Prism] Plugin Prism v3.5.0 generated an exception while executing task 154338
java.lang.IllegalArgumentException: Material cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:60) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at network.darkhelmet.prism.actions.data.ItemStackActionData.toItem(ItemStackActionData.java:204) ~[Prism.jar:?]
	at network.darkhelmet.prism.actions.ItemStackAction.deserialize(ItemStackAction.java:111) ~[Prism.jar:?]
	at network.darkhelmet.prism.database.sql.SqlSelectQueryBuilder.executeSelect(SqlSelectQueryBuilder.java:631) ~[Prism.jar:?]
	at network.darkhelmet.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:66) ~[Prism.jar:?]
	at network.darkhelmet.prism.commands.NearCommand.lambda$handle$0(NearCommand.java:66) ~[Prism.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-138]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
